server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      s3:
        access-key: ${AWS_S3_ACCESS_KEY:test-access-key}
        secret-key: ${AWS_S3_SECRET_KEY:test-secret-key}
        bucket: ${AWS_S3_BUCKET:test-bucket}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_community
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_NAME}
    password: ${LOCAL_MYSQL_PASSWORD}

jwt:
  secret: ${JWT_SECRET:test-secret-key-test-secret-key-test-secret-key-test-secret-key}
  access-expiration-ms: ${ACCESS_EXPIRATION_MS:3600000}
  refresh-expiration-ms: ${REFRESH_EXPIRATION_MS:86400000}


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups.enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    persistAuthorization: true